### ISSUE TITLE
Fix hand mortar spawn

### ISSUE THREAD

**Issue by edawgsnizzle** [edawgsnizzle/JA2-UB-Bigmaps#3]
Theres a script or something that places the hand mortar in sector H11. As a bandaid i have manually placed the item on the map which seems to work exactly as it should. only (Minor) issue is that the original hand mortar still spawns off map and appears in the inventory display.

**Comment by Asdow** [comment]
See the extra items xml files in Data-UB\AddOns\Data-UB-1.13\TableData\Map\ExtraItems

**Comment by edawgsnizzle** [comment]
cant believe i missed this *facepalm* Thanks!
